name: 'push gherkin to notion'

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.feature'

jobs:
  push_to_notion:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: push
        run: node notion_integration.js
